### PR TITLE
added docstring

### PR DESCRIPTION
**Pull request by Ashwin-developer12**
i have added the docstring of the program. i have also fixed some typos. please check them and merge them . will add docstring for all the methods and classes within 2 -3 days . if there is correction , please feel free to tell me

### CODE REVIEW

**Comment by Ashwin-developer12** [comment]
also can you tell me whats exactly happening in the crossover method so that i can include them in the comments 
also what happens at fit.append(pair) (for comments)

**Review by Ashwin-developer12 — COMMENTED** [review]
I've added the docstring of the main program . And fixed some typos. will add the docstring for each function and class in 2 - 3 days

**Review by pandeyganesha — APPROVED** [review]
Thanks for contributing :)

Your edit needs some minor fixes. I'll look after them.

**Comment by pandeyganesha** [comment]
@Ashwin-developer12 

Cross Over: Let's say we have two chromosomes (possible solutions) for the 6x6 problem.
<b>chromosome 1 :</b> 
<table>
<tr>
<td>2</td>
<td>1</td>
<td>3</td>
<td>4</td>
<td>4</td>
<td>5</td>
</tr>
</table>

<b>chromosome 2 : </b>
<table>
<tr>
<td>2</td>
<td>0</td>
<td>1</td>
<td>6</td>
<td>5</td>
<td>4</td>
</tr>
</table>

Now let's randomly choose a crossing over point be 3. so now we will take first 3 elements from the chromosome 1 and rest from the other to make a new chromosome. And the another chromosome would be the first 3 elements from the second and the rest from the chromosome 1. 

So the new chromosomes become:
<table>
<tr>
<td>2</td>
<td>1</td>
<td>3</td>
<td>6</td>
<td>5</td>
<td>4</td>
</tr>
</table>
<table>
<tr>
<td>2</td>
<td>0</td>
<td>1</td>
<td>4</td>
<td>4</td>
<td>5</td>
</tr>
</table>

It same like a child gets features from its both parents randomly.
You can read Readme for more info or watch this video on [Genetic Algo](https://youtu.be/ZdVL5k_Jkbg) by Professor Mausam, IIT Delhi.

**Comment by pandeyganesha** [comment]
@Ashwin-developer12 

fit.append(pair) is adding the fitness of each chromosome in the list. 
Pair is the number of non-attacking pairs of queens (that's our criteria for this problem).
We calculated the fitness for each chromosome and then append that in the list.

Feel free to ask more questions :)

**Comment by Ashwin-developer12** [comment]
Thanks

**Pull request merged**
